### ISSUE TITLE
How to buil a URL?

### ISSUE THREAD

**Issue by americo2015** [spplante/react-content-query#11]
Hi,
I am trying to build a URL that looks like this:
https://my.tenant.com/sites/Demo2/SitePages/Lorem-ipsum-dolor-sit-amet.aspx
to use in a header. 

with FileRef i get this part: /sites/Demo2/SitePages/Lorem-ipsum-dolor-sit-amet.aspx
but I can't find the way to add the first part of the URL, I tried like this in my template:
<a href="https://my.tenant.com" + {{FileRef.textValue}}>{{Title.textValue}}</a>
but it doesn't work.
Could you help me whit this? 
Best regards
Americo

**Comment by spplante** [comment]
Hi @americo2015 , you are not using Javascript you are using a static handlebars template, so no need to do "https://my.tenant.com" + {{token}} like you are doing, you simply have to do it like so :

```html
<a href="https://my.tenant.com{{FileRef.textValue}}">{{Title.textValue}}</a>
```

On another note, not sure why you need to specify an absolute URL, the server relative URL returned by FileRef should be more than enough as it should resolve to the current tenant you are on. Unless you are trying to create a link to another tenant, not sure why you would need an absolute URL?

Hope it helps 👍

**Comment by americo2015** [comment]
Hi,

Thanks it is working with just :
`<a href="{{FileRef.textValue}}">{{Title.textValue}}</a>`
I didn't now that it uses a relative URL. 
Thanks a lot!
👍
