### ISSUE TITLE
Is it possible to provision that webpart with Pnp PowerShell ? 

### ISSUE THREAD

**Issue by benjamingournay2** [spplante/react-content-query#12]
Hi,

Is it possible to provision that webpart with PnP PowerShell in a powershell script ? If yes, how ? 
For example, i can provision a list webpart with the following command:

Add-PnPClientSideWebPart -Page $page -DefaultWebPartType List -Section 1 -Column 1 -WebPartProperties @{isDocumentLibrary="true";selectedListId="$($list.ID)"}

Thks.

Best regards,

**Comment by spplante** [comment]
Hi @benjamingournay2 
I don't see why it wouldn't work, PNP exports and imports all the WebParts the same way. Did you try exporting a page with the WebPart on it to see the resulting JSON?
