### ISSUE TITLE
Is it possible to surface links to Sharepoint library folders?

### ISSUE THREAD

**Issue by spidersbite** [spplante/react-content-query#13]
I am trying to show Folders from a Sharepoint library. 
I've made folder names display but they're just strings of text, not linking to anything.
Is there an additional field I have to pull to link to folders? Is it possible to link to folders?

**Comment by spplante** [comment]
I am not on my computer right now but there is a field that contains the URL for a given item/folder.

Try using the field **FileRef** or **FileLeafRef**, it should work :)

**Comment by spidersbite** [comment]
A combination of the two worked. Thank you!
