### ISSUE TITLE
How can we get urls working from a library?

### ISSUE THREAD

**Issue by spidersbite** [spplante/react-content-query#14]
`We` have a situation where people are putting links in a library. 
Our content query works for files in the library, but not for urls. 

This is what works to pull files. 
`<a href="{{FileRef.textValue}}" target="new">{{{FileLeafRef.htmlValue}}}</a>`
When a link is entered, it attempts to download, and refreshes to the page the user was just on. 

Any suggestions for getting links working appreciated.

**Comment by spplante** [comment]
Not sure I understand your question, are you talking about trying to render a field of type "Url"?

When you say that people are putting links in a library, you mean they add a custom column of type "Url" and they fill that column with a url value, and now you're trying to render that column value?

**Comment by spidersbite** [comment]
I'll try to explain better. This is not a custom column. They are adding a url where you can add a file. You know how there's a dropdown and you can add to a library? See screenshot. They are adding links, and I need to render those values. 
![links](https://user-images.githubusercontent.com/10105838/51565251-80044280-1e5f-11e9-9e81-9a087140fa56.PNG)

**Comment by spplante** [comment]
I just took a look and it's really not straight forward, turns out SPO does not store the URL value within a simply field, it stores it with <in the "Property Bag {{MetaInfo}}" field.

If you try to render {{MetaInfo.textValue}} you will find something along those lines :

```
<vti_parserversion:SR|16.0.0.8509
vti_folderitemcount:IW|0
vti_author:SW|i:0#.f|membership|sp.plante@spptechnologies.onmicrosoft.com
vti_dbschemaversion:SR|16.0.174.0
vti_sprocsschemaversion:SR|16.0.379.0
vti_writevalidationtoken:SW|7foW/wUqbwBl1/5jM5e3sGzhmg8=
vti_modifiedby:SW|i:0#.f|membership|sp.plante@spptechnologies.onmicrosoft.com
vti_foldersubfolderitemcount:IW|0
vti_shortcuturl:SW|https://google.com/
ContentTypeId:SW|0x010100DFE7CEAEF9CAD14BA494BBD2EEA10081
```

As you can see in the snippet above, my real url is located there :

```
vti_shortcuturl:SW|https://google.com/
```

So you would basically have to do some manipulations with  {{MetaInfo.textValue}} in order to extract the URL that you want using helpers like "split" etc...

Here's a complete list of available helpers, try to use them and see if you can extract what you are looking for :

https://github.com/helpers/handlebars-helpers#helpers

**Comment by spidersbite** [comment]
Ok, that is tricky. I will take a look. 

One last question. When I'm using the Content Query with a library and trying to show files, the user experience is that they click a link and it downloads the file. Is there something I can do to make the file open in the browser instead of download?

**Comment by spplante** [comment]
@spidersbite this behavior is the default SPO behavior when referring to a document using the "direct" url. If you take a look at the URL generated by SPO when you put your mouse over a document within a document library, you will notice that SPO does not use a direct url, it uses **/_layouts/Docs.aspx** which is a system page responsible for managing the document opening behavior (whether the document should open in Excel Online, Excel Client, etc...). 

Here's an example of a URL used by SPO for an Excel document :

https://yoursite.sharepoint.com/_layouts/15/Doc.aspx?sourcedoc=%7B0bc722d2-167e-4ad7-98ed-b51874d6821d%7D&action=default&uid=%7B0BC722D2-167E-4AD7-98ED-B51874D6821D%7D&ListItemId=5&ListId=%7BD6BB9C18-79E5-4D0F-99BD-1193FC96F1A2%7D&odsp=1&env=prod

If you inspect this URL, you can basically see that it requires the following parameters :

- **sourcedoc** : The document unique ID which you can get with {{UniqueId.textValue}}
- **uid** : The document unique ID which you can get with  {{UniqueId.textValue}}
- **ListId** : The ID of the list which you can get with {{pageContext.list.id._guid}}
- **ListItemId** : The ID of the item which you can get with {{ID.textValue}}

The final generated url looks like this, I tested it and it works : 

```handlebars
{{#each items}}
    <div class="myItem">
        <a href="https://yoursite.sharepoint.com/_layouts/15/Doc.aspx?sourcedoc=%7B{{UniqueId.textValue}}%7D&action=default&uid=%7B{{UniqueId.textValue}}%7D&ListItemId={{ID.textValue}}&ListId=%7B{{../pageContext.list.id._guid}}%7D&odsp=1&env=prod">Link to my item!</a>
    </div>
{{/each}}
```

**Comment by spidersbite** [comment]
I'll give it a try. Thanks so much for your reply.

**Comment by spidersbite** [comment]
I think I am having trouble with the list ID. It's not a field choice I can enable in the webpart. 
The error I am getting is "Named entity expected. Got none."
Also, above you list sourcedoc and uid as the same thing - {{UniqueId.textValue}}. Is that correct?

**Comment by spplante** [comment]
The **sourcedoc** and **uid** are both the same, don't ask me why this is how SPO builds the URL if you look at a regular document link in SPO.

As for the list ID, it's not a field, it's part of the {{pageContext}} token, which is part of the available tokens as documented [here](https://github.com/spplante/react-content-query#available-tokens).

But I did do a mistake, the current {{pageContext}} will give the you the list on which the current page resides, which is the Site Pages list, and that's not what you need. I don't think we'll be able to provide that one dynamically, so just manually put the ID of your list and you'll be fine.

Edit: Actually and went to see my test page to understand how I made work even though I used the Site Pages list ID, and it simply looks like SPO does NOT need the parameter, as long it has **sourcedoc** is provided, the other parameters aren't required. So this should work just fine :

```handlebars
{{#each items}}
    <div class="myItem">
        <a href="https://yoursite.sharepoint.com/_layouts/15/Doc.aspx?sourcedoc=%7B{{UniqueId.textValue}}%7D&action=default&odsp=1&env=prod">Link to my item!</a>
    </div>
{{/each}}
```

However, just to be consistent with how SPO generates the links, I would still specify all the parameters just in case. You can just hardcode the list ID to the correct target list id. You can find it by clicking "Library Settings" within your target library and take the ID specified in the URL.

**Comment by spidersbite** [comment]
I tried both ways - the longer link with everything specified and the shorter one. 
Both times when I click the link I get 500 INTERNAL SERVER ERROR. 
The template content editor continues to show "Named entity expected. Got none."

**Comment by spplante** [comment]
Did you validate that the link is the exact same as when you hover with your mouse on the official link generated by SharePoint within the document library itself?

Can you paste the original link generated by SharePoint and the one generated by your template?

Paste your handlebars template as well.

Thanks

**Comment by spidersbite** [comment]
On closer inspection there was a small error and I made this work. Thanks as always for your help.
