### ISSUE TITLE
Including custom Handlebar helper

### ISSUE THREAD

**Issue by ytterstrom** [spplante/react-content-query#15]
Hi, and thanks for your webpart. I do not know if you respond to issues when the repo has been moved to the SPFX sample repo.
I have trouble including custom handlebar helpers. When I try to use my helper function in the template by {{#functionname}} I get An error occured while processing the handlebars template : Error: the functioname doesn't match each. Any idea why?

**Comment by spplante** [comment]
Hi there,

Can you provide your js file which contains the code registring the helper? 

Thanks!

**Comment by ytterstrom** [comment]
I tried with the example in readme. I created a file called Helpers.js. I included it in the webpart settings. I have a custom handlebars template and in that I try to call the helper function with both {{test}} and {{#test}}. Have I missed something?
ReactContentQuery.ExternalScripts.Helpers = {
	
    onPreRender: function(wpContext, handlebarsContext) {
        handlebarsContext.registerHelper('test', function (param, options){
            return 'Test';
        })
    },
    
    onPostRender: function(wpContext, handlebarsContext) {
        // Do something after rendering (ie: calling a plugin on the generated HTML)
    }
    
}

**Comment by spplante** [comment]
It looks correct to me (except that technically the handlebars.registerHelpers should have a ";" at the end of its line), I tested it on my side and it works fine :

Here is my script include :
![Step 1](https://i.ibb.co/MPCsxLC/Screenshot1.png)

Here is the script :
![Step 2](https://i.ibb.co/kckXrDf/Screenshot4.png)

How I use it in the template :
![Step 3](https://i.ibb.co/GPpQC8X/Screenshot2.png)

Final result :
![Step 4](https://i.ibb.co/DKZyRNf/Screenshot3.png)

Do you have an error in the console when you use {{test}} without the #?

**Edit :** 

Oh, can you try using a different helper name? Seems like the {{test}} helper already exists in the helpers I automatically add from the handlebars-helpers package :

https://github.com/helpers/handlebars-helpers#test

**Comment by ytterstrom** [comment]
Now it works. Cannot really say why, beacuse I did not change anything. Maybe some weird caching issue on my side. Thanks for your help!
