### ISSUE TITLE
Getting error "Player.Views.AuthV2.js:2 Uncaught (in promise) BrowserAuthError: " when navigating to a page with youtube webparts

### ISSUE THREAD

**Issue by leehumphreys2000** [spplante/react-content-query#20]
On my homepage I have the React Content Query Web Part with a navigation node pointing to a page that has OOB Youtube web parts. When I navigate to the page with the YT web parts, the YT videos do not load. However, if I hit refresh on the YT web part page, the videos then appear. This appears to happen after a period of inactivity, e.g. overnight and login first thing, or after several hours in the day, etc

Also if I go to the page directly using a URL, rather than navigating from another page (note: navigation from another page doesnt use the React Content Query web part) then it just loads the YT videos.

Looking at the F12 debug logs, I am seeing the following error:

Player.Views.AuthV2.js:2 Uncaught (in promise) BrowserAuthError: redirect_in_iframe: Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true
at t [as constructor] (Player.Views.AuthV2.js:2:25691)
at new t (Player.Views.AuthV2.js:2:40813)
at Function.@pa-client/authv2.t.createRedirectInIframeError (Player.Views.AuthV2.js:2:42920)
at Function.@pa-client/authv2.e.blockRedirectInIframe (Player.Views.AuthV2.js:2:119271)
at t.@pa-client/authv2.e.preflightBrowserEnvironmentCheck (Player.Views.AuthV2.js:2:210443)
at t.<anonymous> (Player.Views.AuthV2.js:2:204900)

Getting error "Player.Views.AuthV2.js:2 Uncaught (in promise) BrowserAuthError: " when navigating to a page with youtube webparts

**Comment by spplante** [comment]
Hi @leehumphreys2000,

Repo have been moved [here](https://github.com/pnp/sp-dev-fx-webparts) so issues should be opened over there as well, but you might want to check this out for this particular problem :

https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking

When generating anchors using custom code like SPFx or in this case handlebars, by default they open via a page router to avoid full refresh of the screen, and this is often problematic. By adding the attribute below to your anchor, you tell SharePoint NOT to use the page router which might fix your problem:

```html
data-interception="off"
```

It should look like this :

```html
<a href="https://google.com" data-interception="off">My Link</a>
```
