### ISSUE TITLE
/sites/web Not possible to retrieve

### ISSUE THREAD

**Issue by schneika** [spplante/react-content-query#7]
It is not possible to me to retrieve single Groups/Teamsites, which definetly exists:
An error occured while loading fields : The previously configured web url '/sites/web' is not found anymore. Either leave the WebPart properties as is or select another web url.

**Comment by spplante** [comment]
Hi schneika,

Thank you for posting your issue in here, I received a notification which allowed me to answer your original question in the official repo :

https://github.com/SharePoint/sp-dev-fx-webparts/issues/292

We will continue the conversation over there and I will update this page accordingly. 

Thanks!

**Comment by spplante** [comment]
Issue has been resolved, see the issue 292 on the official repository for the implemented solution :

https://github.com/SharePoint/sp-dev-fx-webparts/issues/292
