### ISSUE TITLE
How do I link to individual items in a list? 

### ISSUE THREAD

**Issue by spidersbite** [spplante/react-content-query#8]
Titles in my Sharepoint list link into individual list items. I want people to click on the linked list item and arrive at the record for that item. I am trying to use Title.htmlvalue in a link <a href={{{... 

No matter what I do I link back to the page where my react content query webpart lives. What can I do to make this work?

**Comment by spplante** [comment]
@spidersbite, the title field behind the scene really just contains the title, it does not contain any kind of link, so trying to specify the title as the "href" of an anchor most likely won't work. However there must be another field like Path or something along those lines that should contain the URL to your list item.

I will try to check this out for you and come back with the correct field that must be used.

**Comment by spplante** [comment]
@spidersbite, I did a quick test and managed to make it work using the following code in the template :

```Handlebars
<a href="{{FileDirRef.textValue}}/DispForm.aspx?ID={{ID.textValue}}" target="_blank">{{Title.textValue}}</a>
```

Essentially, if you look up articles which explains how to link to the display form of an item, they explain that you must generate a link like the following :

**https://MyTenant.sharepoint.com/sites/MySite/MyList/DispForm.aspx?ID=4**

This is basically the URL or your list, followed by **/DispForm.aspx?ID=4** where **4** needs to be replaced by the ID of your item.

Fortunately, the WebPart gives you access to both informations using the following fields :

- Item's parent list url :  **FileDirRef**
- Item's ID : **ID**

Knowing this information, you can now build the link all by yourself 👍 

ProTip : I you want a good way to debug the information within each of your selected fields, just put the following markup at the beginning of your handlebars template :

```
{{log items}}
```

This will basically log the **items** object directly in the console, so you can open the console and inspect in details all your items and their field values. This is an example of what it looks like in the console :

<img src="https://image.ibb.co/cJ9QqH/2018_03_22_15_27_36.png" alt="" />

Let me know if that helps ;)

**Comment by spidersbite** [comment]
It's not working for me yet. Using your code exactly, I get links that look like https://mycompany.com/DispForm.aspx?ID= and go to a 404 error. I need the ID to populate and I need the url to come from the list on a Sharepoint group, so it would be longer like https://mycompany.com/sites/groupname/DispForm.aspx?ID= .

Did I need to change any of the code you gave me? 

Thank you for helping. I am not a developer but I'm trying to learn to use these tools to make better use of modern Sharepoint pages.

**Comment by spplante** [comment]
First of all, in order for your handlebars template to be able to use the fields I gave you in the code, you must select them in the **View Fields** property of the toolpane. Once you will have selected the **ID** and **FileDirRef** fields, their value will be rendered correctly.

Second of all, the url needs to go deeper than the group, it actually needs to go all the way to the list like following :

https://mycompany.com/sites/groupname/listname/DispForm.aspx?ID=4

Once you will have checked the required fields in the webpart **View Fields** section, it will work.

**Comment by spidersbite** [comment]
It works! Thank you so much for your patient explanations and this tool. 🥇

**Comment by spplante** [comment]
Glad you got it working :) Let me know if there is anything else!
